# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\AccessDeniedListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Security\ApiTokenAuthenticator:
        arguments:
            - '@App\Repository\UserRepository'
        tags:
            - { name: monolog.logger, channel: security }