FROM php:8.4-fpm

WORKDIR /var/www/backend

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions pdo_mysql intl zip opcache mongodb

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY backend/ .

RUN composer install \
    --no-dev \
    --optimize-autoloader \
    --no-interaction \
    --no-scripts
