server {
    listen 80;
    server_name localhost;

    # --- FRONTEND (Gère l'affichage, les pages JS, l'Admin, etc.) ---
    location / {
        root /var/www/frontend;
        index index.html;
        # Redirige toutes les URL vers index.html pour que votre Route.js fasse son travail
        try_files $uri $uri/ /index.html;
    }

    # --- BACKEND (Symfony API uniquement) ---
    location /api {
        root /var/www/backend/public;
        # La bonne pratique pour envoyer /api/... vers l'index.php de Symfony
        try_files $uri /index.php$is_args$args;
    }

    # --- Gestion de l'exécution PHP ---
    location ~ ^/index\.php(/|$) {
        root /var/www/backend/public;
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        internal;
    }

    # Sécurité
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}